const content = window.portfolioContent;
const translations = {
  zh: { portfolio: '作品集', available: 'Available for meaningful work', heroLine1: '你好，我是', heroIntro: '我把复杂的事物，做成清晰、好用且有一点点意外的体验。', viewWork: '探索我的作品', scrollNote: '向下走，慢慢认识我', photoPlaceholder: '照片位置', portraitCaption: '留一点空白给未来', about: 'ABOUT', smallThought: 'A small thought', aboutTitle: '好奇心是我的<br><em>工作方法。</em>', aboutText: '我喜欢在设计、技术和叙事的交叉地带工作。比起把答案说得很满，我更在意让一个人愿意停下来、试一下，再发现一件有趣的事。', years: '年探索经验', questions: '还没问完的问题', location: '目前所在时区', experience: 'EXPERIENCE', path: 'The path so far', experienceTitle: '把每一段经历<br><em>变成可复用的能力。</em>', resumeNote: '简历内容可在这里更新 ↗', projects: 'SELECTED WORKS', playground: 'A small playground', projectsTitle: '一些正在发生的<br><em>事情。</em>', videoOnly: '只看有视频的项目', projectLinksNote: '作品图片 / 外部链接的位置已经留好。', startConversation: '从一个想法开始', imagePortfolioTitle: '看见作品，<br><em>再读懂它。</em>', imagePortfolioNote: '图片与文字并置，让每个项目有自己的呼吸。', openTo: 'Open to a good conversation', contactTitle: '不如从<br><em>你好</em>开始。', contactText: '想聊聊一个项目、一个岗位，或者一个还没有名字的想法？这里会收到你的消息。', messageKicker: 'LEAVE A NOTE', messageTitle: '联系 TA', nameLabel: '你的名字', emailLabel: '你的邮箱', messageLabel: '想说的话', sendMessage: '发送留言', lookingFor: '我想去的岗位', rolePlaceholder: '内容待添加', footerText: 'Made with curiosity, kept intentionally unfinished.', modalPlaceholder: '替换成你的项目视频链接' },
  en: { portfolio: 'PORTFOLIO', available: 'Available for meaningful work', heroLine1: 'Hello, I am', heroIntro: 'I turn complex things into clear, useful experiences with a little surprise.', viewWork: 'Explore my work', scrollNote: 'Scroll down, stay a while', photoPlaceholder: 'Photo placeholder', portraitCaption: 'Leave room for what comes next', about: 'ABOUT', smallThought: 'A small thought', aboutTitle: 'Curiosity is my<br><em>working method.</em>', aboutText: 'I work at the intersection of design, technology and storytelling. Rather than filling every answer, I care about making someone pause, try, and discover something unexpected.', years: 'years exploring', questions: 'open questions', location: 'current timezone', experience: 'EXPERIENCE', path: 'The path so far', experienceTitle: 'Turning every chapter<br><em>into a reusable skill.</em>', resumeNote: 'Update your resume here ↗', projects: 'SELECTED WORKS', playground: 'A small playground', projectsTitle: 'Things that are<br><em>in progress.</em>', videoOnly: 'Show video projects only', projectLinksNote: 'Image and external link slots are ready.', startConversation: 'Start with an idea', imagePortfolioTitle: 'See the work,<br><em>then read it.</em>', imagePortfolioNote: 'Images and words sit together, letting every project breathe.', openTo: 'Open to a good conversation', contactTitle: 'Start with<br><em>hello</em>.', contactText: 'A project, a role, or an idea without a name yet. I would love to hear from you.', messageKicker: 'LEAVE A NOTE', messageTitle: 'Contact me', nameLabel: 'Your name', emailLabel: 'Your email', messageLabel: 'Your message', sendMessage: 'Send message', lookingFor: 'ROLE I AM SEEKING', rolePlaceholder: 'Content to be added', footerText: 'Made with curiosity, kept intentionally unfinished.', modalPlaceholder: 'Replace with your project video link' }
};

const renderExperience = () => { document.querySelector('#experience-list').innerHTML = content.experience.map(item => `<article class="timeline-item"><span class="period">${item.period}</span><div class="timeline-role">${item.role}</div><span class="timeline-place">${item.place}</span><p class="timeline-description">${item.description}</p></article>`).join(''); };
const renderProjects = (videoOnly = false) => { const list = videoOnly ? content.projects.filter(project => project.hasVideo) : content.projects; document.querySelector('#project-grid').innerHTML = list.map(project => `<article class="project-card ${project.color}"><div class="project-top"><span>${project.number}</span><span>${project.type}</span></div><div><h3>${project.title}</h3><p>${project.description}</p></div><div class="project-bottom"><a class="project-link ${project.link ? '' : 'empty'}" href="${project.link || '#'}">${project.link ? 'OPEN LINK ↗' : 'LINK TO COME ↗'}</a><span>${project.hasVideo ? 'VIDEO' : 'IMAGE'}</span></div><span class="project-orbit"></span></article>`).join(''); };
const renderShowcase = () => { const gallery = document.querySelector('#showcase-gallery'); const copy = document.querySelector('#showcase-copy'); const updateCopy = index => { const project = content.projects[index]; copy.innerHTML = `<span class="showcase-number">${project.number}</span><p class="kicker">${project.type}</p><h3>${project.title}</h3><p class="showcase-description">${project.description}</p><a class="text-link" href="${project.link || '#contact'}"><span>${project.link ? 'OPEN PROJECT' : 'ADD PROJECT LINK'}</span><span class="arrow">↗</span></a>`; gallery.querySelectorAll('.showcase-thumb').forEach((thumb, thumbIndex) => thumb.classList.toggle('active', thumbIndex === index)); }; gallery.innerHTML = content.projects.map((project, index) => `<button class="showcase-thumb ${index === 0 ? 'active' : ''}" type="button" data-project-index="${index}"><img src="${project.image}" alt="${project.title}" /><span>${project.number} / ${project.type}</span></button>`).join(''); gallery.addEventListener('click', event => { const thumb = event.target.closest('.showcase-thumb'); if (thumb) updateCopy(Number(thumb.dataset.projectIndex)); }); updateCopy(0); };
const setLanguage = lang => { document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en'; document.querySelectorAll('[data-i18n]').forEach(element => { const value = translations[lang][element.dataset.i18n]; if (value) element.innerHTML = value; }); document.querySelector('#language-toggle').textContent = 'EN / 中'; localStorage.setItem('portfolio-lang', lang); };
const renderProfile = () => { document.querySelector('#profile-name').textContent = content.profile.name; document.querySelector('#profile-summary').textContent = content.profile.summary; document.querySelector('#profile-intent').textContent = content.profile.intent; document.querySelector('#profile-direction').textContent = content.profile.direction; document.querySelector('#profile-city').textContent = content.profile.city; document.querySelector('.profile-contact-info a[href^="tel:"]').textContent = content.profile.phone; document.querySelector('.profile-contact-info a[href^="mailto:"]').textContent = content.profile.email; };

renderProfile(); renderExperience(); renderProjects(); renderShowcase();
setLanguage(localStorage.getItem('portfolio-lang') || 'zh');
document.querySelector('#language-toggle').addEventListener('click', () => setLanguage(document.documentElement.lang === 'zh-CN' ? 'en' : 'zh'));
document.querySelector('#theme-toggle').addEventListener('click', () => { document.body.classList.toggle('dark'); localStorage.setItem('portfolio-theme', document.body.classList.contains('dark') ? 'dark' : 'light'); });
if (localStorage.getItem('portfolio-theme') === 'dark') document.body.classList.add('dark');
document.querySelector('#video-filter').addEventListener('click', event => { const active = event.currentTarget.classList.toggle('active'); renderProjects(active); });
const modal = document.querySelector('#video-modal'); document.querySelector('#open-video')?.addEventListener('click', () => { modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); }); document.querySelectorAll('[data-close-modal]').forEach(element => element.addEventListener('click', () => { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); }));
document.addEventListener('keydown', event => { if (event.key === 'Escape') modal.classList.remove('open'); });
document.querySelector('#message-form').addEventListener('submit', event => { event.preventDefault(); document.querySelector('#form-feedback').textContent = document.documentElement.lang === 'zh-CN' ? '留言已准备好，感谢你的来信。' : 'Your note is ready. Thank you for reaching out.'; event.currentTarget.reset(); });
const glow = document.querySelector('.cursor-glow'); window.addEventListener('pointermove', event => { glow.style.left = `${event.clientX}px`; glow.style.top = `${event.clientY}px`; });
